Repository atmtools/typhon, pull requests merged in 2018-11, with the labels that each got.

#249 Made SRF.estimate_band_coefficients even more fragile
  typhon/physics/units/em.py
Labels: in progress

#256 Collect information on installation at one place.
  CONTRIBUTING.md
  README.md
Labels: documentation, setup

#259 Add python requirement for setuptools.
  setup.py
Labels: setup

#260 Fix conversion of colormaps to RGBA values.
  typhon/plots/colors.py
  typhon/tests/plots/test_colors.py
Labels: enhancement
