Repository atmtools/typhon, pull requests merged in 2019-02, with the labels that each got.

#280 Ensure NetCDF4 returns times correctly, even when scale factor is set.
  typhon/files/handlers/common.py
  typhon/tests/files/handlers/test_netcdf4.py
Labels: bug

#278 Don't crash on scalar data variables with fill value set
  typhon/files/handlers/common.py
  typhon/tests/files/handlers/test_netcdf4.py
Labels: bug

#281 Improve calculation of saturation pressure for the mixed-phase
  typhon/constants.py
  typhon/physics/atmosphere.py
  typhon/physics/thermodynamics.py
Labels: API changes, enhancement, feature

#285 Make symbols in thermodynamic equations consistent
  typhon/physics/atmosphere.py
Labels: documentation
