Repository atmtools/typhon, pull requests merged in 2019-04, with the labels that each got.

#290 Update package description and meta information
  DESCRIPTION.rst
  setup.py
Labels: setup

#291 Add ``.zenodo.json``
  .zenodo.json
Labels: setup

#296 Extend contribution guidelines
  CONDA-ENV.md
  CONTRIBUTING.md
  GITHUB-INTRO.md
Labels: documentation

#297 Add Python 3.7 to Travis build matrix
  .travis.yml
Labels: setup

#298 Add ASTER class
  .travis.yml
  doc/conf.py
  doc/modules.rst
  doc/typhon.cloudmask.aster.rst
  doc/typhon.cloudmask.cloudstatistics.rst
  doc/typhon.cloudmask.rst
  environment.yml
  requirements.txt
  setup.py
  typhon/cloudmask/__init__.py
  typhon/cloudmask/aster.py
  typhon/math/common.py
Labels: enhancement, feature, setup

#299 Change cloudmask type to float
  typhon/cloudmask/aster.py
Labels: enhancement
